### ISSUE TITLE
如何生成exe文件？

### ISSUE THREAD

**Issue by Roihn** [HakuRemu/ZhouShen_Hime#1]
您好！目前我想要在您的代码的框架下做些专属的修改，目前程序已经修改完成，但在生成exe文件的时候出现了问题，不知您这边能否教教我，是在什么环境下以什么指令生成了单独可用的exe文件，谢谢！

**Comment by LGKKY** [comment]
看了下更新历史 似乎用的是nuitka编译




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月1日(周六) 晚上8:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [HakuRemu/ZhouShen_Hime] 如何生成exe文件？ (#1)




 
您好！目前我想要在您的代码的框架下做些专属的修改，目前程序已经修改完成，但在生成exe文件的时候出现了问题，不知您这边能否教教我，是在什么环境下以什么指令生成了单独可用的exe文件，谢谢！

**Comment by Roihn** [comment]
确实用nuitka可以实现，我原先一直在尝试Pyinstaller，非常感谢！
